version: "2"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    image: noordwind/collectively.api
    links:
      - rabbitmq
      - storage-service
    ports:
      - '5000:5000'

  storage-service:
    image: noordwind/collectively.services.storage
    links:
      - mongo
      - rabbitmq
      - users-service
      - remarks-service
      - operations-service
      - statistics-service
    ports:
      - '10000:10000'  

  users-service:
    image: noordwind/collectively.services.users
    links:
      - mongo
      - rabbitmq
    ports:
      - '10001:10001'

  remarks-service:
    image: noordwind/collectively.services.remarks
    links:
      - mongo
      - rabbitmq
    ports:
      - '10002:10002'    

  operations-service:
    image: noordwind/collectively.services.operations
    links:
      - mongo
      - rabbitmq
    ports:
      - '10010:10010'

  medium-service:
    image: noordwind/collectively.services.medium
    links:
      - mongo
      - rabbitmq
    ports:
      - '11100:11100'

  mailing-service:
    image: noordwind/collectively.services.mailing
    links:
      - mongo
      - rabbitmq
    ports:
      - '10005:10005'     

  statistics-service:
    image: noordwind/collectively.services.statistics
    links:
      - mongo
      - rabbitmq
    ports:
      - '10006:10006'  

  supervisor-service:
    image: noordwind/collectively.services.supervisor
    links:
      - mongo
      - rabbitmq
      - api
      - mailing-service
      - medium-service
      - operations-service
      - remarks-service
      - statistics-service
      - storage-service
      - users-service
    ports:
      - '11000:11000'

  websockets-service:
    image: noordwind/collectively.services.websockets
    links:
      - rabbitmq
    ports:
      - '15000:15000'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
