version: "2"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ./Collectively.Api/Collectively.Api
    links:
      - rabbitmq
      - storage-service
    ports:
      - '5000:5000'

  storage-service:
    build: ./Collectively.Services.Storage/Collectively.Services.Storage
    links:
      - mongo
      - rabbitmq
      - users-service
      - remarks-service
      - operations-service
      - statistics-service
    ports:
      - '10000:10000'  

  users-service:
    build: ./Collectively.Services.Users/Collectively.Services.Users
    links:
      - mongo
      - rabbitmq
    ports:
      - '10001:10001'

  remarks-service:
    build: ./Collectively.Services.Remarks/Collectively.Services.Remarks
    links:
      - mongo
      - rabbitmq
    ports:
      - '10002:10002'    

  operations-service:
    build: ./Collectively.Services.Operations/Collectively.Services.Operations
    links:
      - mongo
      - rabbitmq
    ports:
      - '10010:10010'

  medium-service:
    build: ./Collectively.Services.Medium/Collectively.Services.Medium
    links:
      - mongo
      - rabbitmq
    ports:
      - '11100:11100'

  mailing-service:
    build: ./Collectively.Services.Mailing/Collectively.Services.Mailing
    links:
      - mongo
      - rabbitmq
    ports:
      - '10005:10005'     

  statistics-service:
    build: ./Collectively.Services.Statistics/Collectively.Services.Statistics
    links:
      - mongo
      - rabbitmq
    ports:
      - '10006:10006'  

  supervisor-service:
    build: ./Collectively.Services.Supervisor/Collectively.Services.Supervisor
    links:
      - mongo
      - rabbitmq
      - api
      - mailing-service
      - medium-service
      - operations-service
      - remarks-service
      - statistics-service
      - storage-service
      - users-service
    ports:
      - '11000:11000'

  websockets-service:
    build: ./Collectively.Services.Websockets/src
    links:
      - rabbitmq
    ports:
      - '15000:15000'

  web:
    build: ./Collectively.Web
    links:
      - api
      - websockets-service
    ports:
      - '9000:9000'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
